In [1]:
import numpy as np
class Solution:
    def global_alignment(self, sequence_A: str, sequence_B:str, substitution: dict, gap: int ) -> tuple:
        n, m = len(sequence_A), len(sequence_B)
        D = [[0]*(m+1) for i in range(n+1)]
        for i in range(1, n+1):
            D[i][0] = D[i-1][0] + gap_penalty
        for j in range(1, m+1):
            D[0][j] = D[0][j-1] + gap_penalty

        for i in range(1, n+1):
            for j in range(1, m+1):
                _match = D[i-1][j-1] + substitution_matrix[sequence_A[i-1]][sequence_B[j-1]]
                _delete = D[i-1][j] + gap_penalty
                _insert = D[i][j-1] + gap_penalty
                D[i][j] = max(_match, _delete, _insert)
        
      
        possible_alignments = []
        backtrack = [(n, m, "", "")]
        while backtrack:
            i, j, alignment_A, alignment_B = backtrack.pop()
            if i == 0 and j == 0:
                possible_alignments.append((alignment_A[::-1], alignment_B[::-1]))
            else:
                if i > 0 and j > 0 and D[i][j] == D[i-1][j-1] + substitution_matrix[sequence_A[i-1]][sequence_B[j-1]]:
                    backtrack.append((i-1, j-1, alignment_A + sequence_A[i-1], alignment_B + sequence_B[j-1]))
                if i > 0 and D[i][j] == D[i-1][j] + gap_penalty:
                    backtrack.append((i-1, j, alignment_A + sequence_A[i-1], alignment_B + "-"))
                if j > 0 and D[i][j] == D[i][j-1] + gap_penalty:
                    backtrack.append((i, j-1, alignment_A + "-", alignment_B + sequence_B[j-1]))
        print(np.matrix(D))
        return possible_alignments


s = Solution()
sequence_A = input("Enter Sequence A:")
sequence_B = input("Enter Sequence B:")
gap_penalty=int(input("Gap penalty :"))
match_score = +1
mismatch_score = -1
substitution_matrix={}
for i in set(sequence_A+sequence_B):
  dict={}
  for j in set(sequence_A+sequence_B):
    if i==j:
      dict[j]=match_score
    else:
      dict[j]=mismatch_score
  substitution_matrix[i]=dict
list_of_alignments = s.global_alignment(sequence_A, sequence_B, substitution_matrix, gap_penalty)
print(list_of_alignments)

[[  0  -2  -4  -6  -8]
 [ -2   1  -1  -3  -5]
 [ -4  -1   0   0  -2]
 [ -6  -3  -2  -1   1]
 [ -8  -5  -4  -3  -1]
 [-10  -7  -4  -5  -3]]
[('A-CTAG', 'AGCT--')]
