In [2]:
import numpy as np

class Solution:
    def local_alignment(self, sequence_A: str, sequence_B:str, substitution: dict, gap: int ) -> tuple:
        n, m = len(sequence_A), len(sequence_B)
        D = [[0]*(m+1) for i in range(n+1)]
        max_score = 0
        max_pos = None

        for i in range(1, n+1):
            for j in range(1, m+1):
                _match = D[i-1][j-1] + substitution_matrix[sequence_A[i-1]][sequence_B[j-1]]
                _delete = D[i-1][j] + gap_penalty
                _insert = D[i][j-1] + gap_penalty
                D[i][j] = max(0, _match, _delete, _insert)
                if D[i][j] > max_score:
                    max_score = D[i][j]
                    max_pos = (i, j)
        
        possible_alignments = []
        i, j = max_pos
        alignment_A, alignment_B = "", ""
        while D[i][j] != 0:
            if D[i][j] == D[i-1][j-1] + substitution_matrix[sequence_A[i-1]][sequence_B[j-1]]:
                alignment_A = sequence_A[i-1] + alignment_A
                alignment_B = sequence_B[j-1] + alignment_B
                i -= 1
                j -= 1
            elif D[i][j] == D[i-1][j] + gap:
                alignment_A = sequence_A[i-1] + alignment_A
                alignment_B = "-" + alignment_B
                i -= 1
            else:
                alignment_A = "-" + alignment_A
                alignment_B = sequence_B[j-1] + alignment_B
                j -= 1

        possible_alignments.append((alignment_A, alignment_B))
        
        print(np.matrix(D))
        return possible_alignments[0]

s = Solution()
sequence_A = input("Enter Sequence A:")
sequence_B = input("Enter Sequence B:")
gap_penalty=int(input("Gap penalty :"))
match_score = +1
mismatch_score = -1
substitution_matrix={}
for i in set(sequence_A+sequence_B):
  dict={}
  for j in set(sequence_A+sequence_B):
    if i==j:
      dict[j]=match_score
    else:
      dict[j]=mismatch_score
  substitution_matrix[i]=dict
alignment = s.local_alignment(sequence_A, sequence_B, substitution_matrix, gap_penalty)
print("Alignment:", alignment)

[[0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 1 0 0 0]
 [0 0 0 2 0 1]
 [0 1 0 0 1 0]
 [0 0 2 0 0 0]]
Alignment: ('TA', 'TA')
